#!/usr/bin/env zsh

# Source zshrc to ensure PATH is set correctly
if [ -f ~/.zshrc ]; then
    source ~/.zshrc
fi

# Ejecutar el build
echo "Building the project..."

if ! ./scripts/generate_doc.sh; then
    echo "Build failed generating docs."
    exit 1
fi

if ! ./scripts/generate_gql.sh; then
    echo "Build failed generating gql."
    exit 1
fi

if ! go build ; then
    echo "Build failed building."
    exit 1
fi

rm ordersgo

echo "Build and tests passed. Proceeding with commit."