# Docker produccion o stage
FROM golang:1.22.6-bullseye

WORKDIR /go/src/github.com/nmarsollier/ordersgo
RUN curl -L https://github.com/nmarsollier/ordersgo/tarball/master | tar xz --strip=1
RUN go install /go/src/github.com/nmarsollier/ordersgo

ENV MONGO_URL=mongodb://host.docker.internal:27017
ENV RABBIT_URL=amqp://host.docker.internal
ENV AUTH_SERVICE_URL=http://host.docker.internal:3000

# Puerto de Auth Service
EXPOSE 3004

CMD ["ordersgo"]

